### PR TITLE
SDL build also needs a few fixes

### PR DESCRIPTION
**Pull request by ChristophHaag**
This one builds with
`cmake -DUSE_OSVR=1 -DUSE_OCULUSSDK=0 -DUSE_SIXENSE=0 -DGL_FRAMEWORK=SDL ..`
and runs.

Still have to figure out why it displays a standard 2d window though.

### CODE REVIEW

**Comment by jimbo00000** [comment]
Thanks again for the changes. How does it work with `-DUSE_OSVR=0 -DUSE_OCULUSSDK=1`? I haven't gotten OSVR and the Rift plugin building on Linux yet.

**Comment by ChristophHaag** [comment]
Not good:
```
Calling initVR...
initVR(1) complete.

Program received signal SIGILL, Illegal instruction.
0x00000000004339dd in OVR::Matrix4<float>::Inverted (this=0x7fffffffcf90) at /usr/include/ovr-0.5.0.1/LibOVR/Include/Extras/OVR_Math.h:2155
2155            OVR_MATH_ASSERT(det != 0);
(gdb) bt
#0  0x00000000004339dd in OVR::Matrix4<float>::Inverted (this=0x7fffffffcf90) at /usr/include/ovr-0.5.0.1/LibOVR/Include/Extras/OVR_Math.h:2155
#1  0x00000000004332f3 in OVRScene::timestep (this=0x653c60 <g_app+704>, dt=0.71344688300000003) at /home/chris/build/RiftSkeleton/src/Scene/OVRScene.cpp:205
#2  0x00000000004238a0 in AppSkeleton::timestep (this=0x6539a0 <g_app>, absTime=0.71344688300000003, dt=0.71344688300000003) at /home/chris/build/RiftSkeleton/src/AppSkeleton/AppSkeleton.cpp:307
#3  0x0000000000429ec6 in OVRSDK05AppSkeleton::timestep (this=0x6539a0 <g_app>, absTime=0.71344688300000003, dt=0.71344688300000003) at /home/chris/build/RiftSkeleton/src/AppSkeleton/OVRSDK05AppSkeleton.cpp:410
#4  0x000000000041f327 in timestep () at /home/chris/build/RiftSkeleton/src/sdl_main.cpp:122
#5  0x0000000000421650 in main (argc=2, argv=0x7fffffffd718) at /home/chris/build/RiftSkeleton/src/sdl_main.cpp:953
(gdb)
```

**Comment by ChristophHaag** [comment]
Why...

ovrmath

**Comment by ChristophHaag** [comment]
Aha, that's why. `__builtin_trap() also generates an ud2`. An error message wouldn't have worked better?

So when `Orientation = {x = 0, y = 0, z = 0, w = 0}`, then Inverting won't work. I tried removing the Inverted() call from https://github.com/jimbo00000/RiftSkeleton/blob/035e9bc6043679948e8e6a89a8063dce10a1ddb7/src/Scene/OVRScene.cpp#L205. Then it seems to work, but I only see a black window. But that could be another problem with the Oculus Rift SDK that also happens in JanusVR and Hi-Fi.

**Pull request merged**
