### PR TITLE
No wonder OSVR didn't do anything on linux

### PR DESCRIPTION
**Pull request by ChristophHaag**

### CODE REVIEW

**Comment by ChristophHaag** [comment]
It's not perfect, but it picks up tracking. I have a feeling it's only orientation and not position tracking, but that's only a minor detail to fix I guess.

It also only works with an unrotated rift, so this video is rotated for displaying on youtube:
https://www.youtube.com/watch?v=J0_F_oBkQDk

**Comment by jimbo00000** [comment]
From the looks of your video, it appears your glm library might be interpreting radian rotation values as degrees(that should be two concentric rings of cubes). Are you perhaps using an older(<0.9.5) version of glm, or have GLM_FORCE_RADIANS turned off? [relevant post](http://www.g-truc.net/post-0623.html)

Still working on that OSVR Oculus Rift plugin build...

**Comment by jimbo00000** [comment]
Got the plugin building and fixed the SDL/OSVR target to correctly place the window at 0,0 on its own X Screen. I notice a lot of tracking latency with VSync on, so turned it off by default. Both positional and rotation tracking work fine on my system - I'd be curious to hear if it works for you.

**Comment by ChristophHaag** [comment]
You are right, I had a very old glm package installed. With an up to date one, rotation works right so you can revert https://github.com/ChristophHaag/RiftSkeleton/commit/4bb04354025890bdb5234afe6ad4c45eef038de3.

Now the only thing left to do is to automatically match the rotation, i.e. render in 1080x1920 with an unrotated rift and in 1920x1080 @ 90° rotated when it is rotated. I looked a bit through the code and there are several places where width and height have simply been switched and that's not the most intuitive way...

**Pull request merged**
